# This docker compose file contains all the services required for running locally or end-to-end tests for all services.

name: world-id-protocol-services
services:  # world-id-indexer
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=indexer_tests
  # world-id-gateway
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
  oprf-key-gen0:
    # this tag/sha must match the versions of taceo crates in Cargo.toml
    image: ghcr.io/taceolabs/oprf-service/oprf-key-gen:v1.1.0-rc.8
    network_mode: "host"
    environment:
      RUST_LOG: "taceo=trace,warn"
      TACEO_OPRF_KEY_GEN__SERVICE__ENVIRONMENT: dev
      TACEO_OPRF_KEY_GEN__BIND_ADDR: 0.0.0.0:20000
      TACEO_OPRF_KEY_GEN__SERVICE__OPRF_KEY_REGISTRY_CONTRACT:
      TACEO_OPRF_KEY_GEN__SERVICE__RPC__HTTP_URLS: http://127.0.0.1:8545
      TACEO_OPRF_KEY_GEN__SERVICE__RPC__WS_URL: ws://127.0.0.1:8545
      # anvil signer 7
      TACEO_OPRF_KEY_GEN__SERVICE__WALLET_PRIVATE_KEY: 0x4bbbf85ce3377467afe5d46f804f221813b2bb87f24d81f60f1fcdbf7cbf4356
      TACEO_OPRF_KEY_GEN__SERVICE__EXPECTED_NUM_PEERS: 3
      TACEO_OPRF_KEY_GEN__SERVICE__EXPECTED_THRESHOLD: 2
      TACEO_OPRF_KEY_GEN__SERVICE__ZKEY_PATH: /app/OPRFKeyGen.13.arks.zkey
      TACEO_OPRF_KEY_GEN__SERVICE__WITNESS_GRAPH_PATH: /app/OPRFKeyGenGraph.13.bin
      TACEO_OPRF_KEY_GEN__SERVICE__CONFIRMATIONS_FOR_TRANSACTION: 1
      TACEO_OPRF_KEY_GEN__POSTGRES__CONNECTION_STRING: postgres://postgres:postgres@localhost:5432/postgres
      TACEO_OPRF_KEY_GEN__POSTGRES__SCHEMA: oprf0
  oprf-key-gen1:
    # this tag/sha must match the versions of taceo crates in Cargo.toml
    image: ghcr.io/taceolabs/oprf-service/oprf-key-gen:v1.1.0-rc.8
    network_mode: "host"
    environment:
      RUST_LOG: "taceo=trace,warn"
      TACEO_OPRF_KEY_GEN__SERVICE__ENVIRONMENT: dev
      TACEO_OPRF_KEY_GEN__BIND_ADDR: 0.0.0.0:20001
      TACEO_OPRF_KEY_GEN__SERVICE__OPRF_KEY_REGISTRY_CONTRACT:
      TACEO_OPRF_KEY_GEN__SERVICE__RPC__HTTP_URLS: http://127.0.0.1:8545
      TACEO_OPRF_KEY_GEN__SERVICE__RPC__WS_URL: ws://127.0.0.1:8545
      # anvil signer 8
      TACEO_OPRF_KEY_GEN__SERVICE__WALLET_PRIVATE_KEY: 0xdbda1821b80551c9d65939329250298aa3472ba22feea921c0cf5d620ea67b97
      TACEO_OPRF_KEY_GEN__SERVICE__EXPECTED_NUM_PEERS: 3
      TACEO_OPRF_KEY_GEN__SERVICE__EXPECTED_THRESHOLD: 2
      TACEO_OPRF_KEY_GEN__SERVICE__ZKEY_PATH: /app/OPRFKeyGen.13.arks.zkey
      TACEO_OPRF_KEY_GEN__SERVICE__WITNESS_GRAPH_PATH: /app/OPRFKeyGenGraph.13.bin
      TACEO_OPRF_KEY_GEN__SERVICE__CONFIRMATIONS_FOR_TRANSACTION: 1
      TACEO_OPRF_KEY_GEN__POSTGRES__CONNECTION_STRING: postgres://postgres:postgres@localhost:5432/postgres
      TACEO_OPRF_KEY_GEN__POSTGRES__SCHEMA: oprf1
  oprf-key-gen2:
    # this tag/sha must match the versions of taceo crates in Cargo.toml
    image: ghcr.io/taceolabs/oprf-service/oprf-key-gen:v1.1.0-rc.8
    network_mode: "host"
    environment:
      RUST_LOG: "taceo=trace,warn"
      TACEO_OPRF_KEY_GEN__SERVICE__ENVIRONMENT: dev
      TACEO_OPRF_KEY_GEN__BIND_ADDR: 0.0.0.0:20002
      TACEO_OPRF_KEY_GEN__SERVICE__OPRF_KEY_REGISTRY_CONTRACT:
      TACEO_OPRF_KEY_GEN__SERVICE__RPC__HTTP_URLS: http://127.0.0.1:8545
      TACEO_OPRF_KEY_GEN__SERVICE__RPC__WS_URL: ws://127.0.0.1:8545
      # anvil signer 9
      TACEO_OPRF_KEY_GEN__SERVICE__WALLET_PRIVATE_KEY: 0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6
      TACEO_OPRF_KEY_GEN__SERVICE__EXPECTED_NUM_PEERS: 3
      TACEO_OPRF_KEY_GEN__SERVICE__EXPECTED_THRESHOLD: 2
      TACEO_OPRF_KEY_GEN__SERVICE__ZKEY_PATH: /app/OPRFKeyGen.13.arks.zkey
      TACEO_OPRF_KEY_GEN__SERVICE__WITNESS_GRAPH_PATH: /app/OPRFKeyGenGraph.13.bin
      TACEO_OPRF_KEY_GEN__SERVICE__CONFIRMATIONS_FOR_TRANSACTION: 1
      TACEO_OPRF_KEY_GEN__POSTGRES__CONNECTION_STRING: postgres://postgres:postgres@localhost:5432/postgres
      TACEO_OPRF_KEY_GEN__POSTGRES__SCHEMA: oprf2
  ohttp-gateway:
    image: ghcr.io/worldcoin/ohttp-tools/ohttp-gateway:latest
    platform: linux/amd64
    ports:
      - "9090:8080"
    environment:
      SEED_SECRET_KEY: "0000000000000000000000000000000000000000000000000000000000000001"
      ALLOWED_TARGET_ORIGINS: "localhost:8080,localhost:8081"
      TARGET_REWRITES: '{"localhost:8080": {"Scheme": "http", "Host": "host.docker.internal:8080"}, "localhost:8081": {"Scheme": "http", "Host": "host.docker.internal:8081"}}'
