[package]
name = "ownership_proof"
type = "bin"
descrption = "UNAUDITED. ALPHA. Noir Circuit Implementation of WIP-103 (Proof of Ownership) for the World ID Protocol."
authors = ["@dkales"]
license = "MIT"
backend = "provekit"

[dependencies]
poseidon2 = { tag = "v0.8.0", git = "https://github.com/TaceoLabs/noir-poseidon", directory = "poseidon2" }
eddsa_poseidon2 = { tag = "v0.8.0", git = "https://github.com/TaceoLabs/noir-poseidon", directory = "eddsa_poseidon2" }
