// SPDX-License-Identifier: MIT
// Generated by: cargo run -p xtask -- gen-alloc --root 1000 --issuers 1 --oprf-keys 1
pragma solidity ^0.8.28;

import {Script, console2} from "forge-std/Script.sol";
import {MockRegistry, MockIssuerRegistry, MockOprfRegistry} from "../../test/crosschain/helpers/Mocks.sol";

contract BootstrapRegistries is Script {
    function run() public {
        vm.startBroadcast();

        MockRegistry registry = new MockRegistry();
        registry.setLatestRoot(1000);

        MockIssuerRegistry issuerRegistry = new MockIssuerRegistry();
        issuerRegistry.setPubkey(1, 11, 12);

        MockOprfRegistry oprfRegistry = new MockOprfRegistry();
        oprfRegistry.setKey(1, 13, 14);

        vm.stopBroadcast();

        string memory json = "bootstrap";
        vm.serializeAddress(json, "registry", address(registry));
        vm.serializeAddress(json, "issuerRegistry", address(issuerRegistry));
        string memory out = vm.serializeAddress(json, "oprfRegistry", address(oprfRegistry));
        vm.writeJson(out, "test/crosschain/fixtures/bootstrap_addrs.json");

        console2.log("Registry:", address(registry));
        console2.log("IssuerRegistry:", address(issuerRegistry));
        console2.log("OprfRegistry:", address(oprfRegistry));
    }
}
