[package]
name = "world-id-core"
version = "0.1.0"
build = "build.rs"
license.workspace = true
edition.workspace = true

[[bin]]
name = "authenticator"
path = "bin/authenticator.rs"

[[bin]]
name = "rp"
path = "bin/rp.rs"

[dependencies]
alloy = { version = "1.0.36", features = ["contract", "signer-local", "sol-types"], default-features = false }
ark-bn254 = { workspace = true }
ark-ff = { workspace = true }
anyhow = { workspace = true }
ciborium = "0.2.2"
hex = { workspace = true }
ruint = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
eddsa-babyjubjub = { git = "https://github.com/TaceoLabs/nullifier-oracle-service.git" }
serde_json = { workspace = true }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
oprf-client = { git = "https://github.com/TaceoLabs/nullifier-oracle-service.git" }
oprf-types = { git = "https://github.com/TaceoLabs/nullifier-oracle-service.git" }
oprf-core = { git = "https://github.com/TaceoLabs/nullifier-oracle-service.git" }
oprf-test = { git = "https://github.com/TaceoLabs/nullifier-oracle-service.git" }
circom-types = { git = "https://github.com/TaceoLabs/co-snarks.git", default-features = false }
ark-serde-compat = { git = "https://github.com/TaceoLabs/nullifier-oracle-service.git" }
poseidon2 = { git = "https://github.com/TaceoLabs/nullifier-oracle-service.git" }
rand = "0.8.5"
ark-ec = "0.5.0"
uuid = "1.14.0"
witness = { git = "https://github.com/TaceoLabs/circom-witness-rs.git"}
eyre = "0.6.12"
groth16 = { git = "https://github.com/TaceoLabs/groth16.git" }
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
base64 = { version = "0.22", optional = true }
time = { version = "0.3", features = ["parsing", "formatting", "serde", "macros"], optional = true }
sha2 = { version = "0.10", optional = true }

[features]
default = []
requests = ["dep:base64", "dep:time", "dep:sha2"]

