[package]
name = "world-id-core"
version = "0.1.0"
build = "build.rs"
license.workspace = true
edition.workspace = true

[dependencies]
alloy = { version = "1.0.36", features = ["contract", "signer-local", "sol-types"], default-features = false }
ark-babyjubjub = { workspace = true }
ark-bn254 = { workspace = true }
ark-ff = { workspace = true }
anyhow = { workspace = true }
ciborium = "0.2.2"
hex = { workspace = true }
ruint = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

