//! Demo passkey ownership proof helpers.
//!
//! This module supports the unaudited WebAuthn/passkey ownership demo circuit in
//! `crates/proof/noir/passkey-ownership-proof`. The stable helpers are usable
//! without proving artifacts; actual ProveKit prove/verify entrypoints are
//! feature-gated.

use ark_babyjubjub::Fq;
use ark_ff::{AdditiveGroup as _, PrimeField as _};
use provekit_common::{InputMap, InputValue, NoirElement};
use world_id_primitives::{FieldElement, TREE_DEPTH, merkle::MerkleInclusionProof};

use crate::{NoirCircuitInput, NoirRepresentable, ProofError, WhirR1CSProof};

/// Number of authenticator slots committed by the demo circuit.
pub const PASSKEY_OWNERSHIP_NUM_SLOTS: usize = 7;
/// Number of 120-bit limbs used for P-256 field/scalar values.
pub const P256_LIMBS: usize = 3;
/// Number of signed nibble slices expected by `noir_bigcurve`.
pub const P256_SCALAR_SLICES: usize = 65;
/// Maximum `clientDataJSON` byte length accepted by the demo circuit.
pub const CLIENT_DATA_JSON_MAX_LEN: usize = 256;
/// Maximum `authenticatorData` byte length accepted by the demo circuit.
pub const AUTHENTICATOR_DATA_MAX_LEN: usize = 64;

const DS_PASSKEY_SLOT: &[u8] = b"WID_PASSKEY_SLOT_V1";
const DS_MIXED_AUTH_SET: &[u8] = b"WID_MIXED_AUTH_SET_V1";

/// P-256 affine public key bytes in big-endian WebAuthn form.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PasskeyPublicKey {
    /// P-256 x-coordinate, big-endian.
    pub x: [u8; 32],
    /// P-256 y-coordinate, big-endian.
    pub y: [u8; 32],
}

impl PasskeyPublicKey {
    /// Returns the x-coordinate split into `[low, mid, high]` 120-bit limbs.
    #[must_use]
    pub fn x_limbs(self) -> [u128; P256_LIMBS] {
        p256_be_bytes_to_limbs(self.x)
    }

    /// Returns the y-coordinate split into `[low, mid, high]` 120-bit limbs.
    #[must_use]
    pub fn y_limbs(self) -> [u128; P256_LIMBS] {
        p256_be_bytes_to_limbs(self.y)
    }
}

/// WebAuthn/P-256 witness values that are specific to the BigCurve verifier.
#[derive(Debug, Clone)]
pub struct WebAuthnWitness {
    /// P-256 public key x-coordinate bytes.
    pub public_key_x: [u8; 32],
    /// P-256 public key y-coordinate bytes.
    pub public_key_y: [u8; 32],
    /// Raw `r || s` P-256 ECDSA signature bytes.
    pub signature: [u8; 64],
    /// Raw `clientDataJSON` bytes, unpadded.
    pub client_data_json: Vec<u8>,
    /// Raw WebAuthn `authenticatorData` bytes, unpadded.
    pub authenticator_data: Vec<u8>,
    /// Index where the base64url-encoded challenge starts inside `clientDataJSON`.
    pub challenge_index: u32,
    /// Private helper witness: y-coordinate of the recovered ECDSA `R` point.
    pub r_point_y: [u8; 32],
    /// SHA-256 signed message digest limbs.
    pub message_limbs: [u128; P256_LIMBS],
    /// Public key x-coordinate limbs.
    pub public_key_x_limbs: [u128; P256_LIMBS],
    /// Public key y-coordinate limbs.
    pub public_key_y_limbs: [u128; P256_LIMBS],
    /// Signature `r` limbs.
    pub signature_r_limbs: [u128; P256_LIMBS],
    /// Signature `s` limbs.
    pub signature_s_limbs: [u128; P256_LIMBS],
    /// `r_point_y` limbs.
    pub r_point_y_limbs: [u128; P256_LIMBS],
    /// `(message / s)` scalar limbs.
    pub s_g_limbs: [u128; P256_LIMBS],
    /// `(message / s)` signed nibble slices.
    pub s_g_slices: [u8; P256_SCALAR_SLICES],
    /// `(message / s)` skew flag.
    pub s_g_skew: bool,
    /// `(message / s)` low borrow flag.
    pub s_g_borrow_low: bool,
    /// `(message / s)` mid borrow flag.
    pub s_g_borrow_mid: bool,
    /// `(r / s)` scalar limbs.
    pub s_p_limbs: [u128; P256_LIMBS],
    /// `(r / s)` signed nibble slices.
    pub s_p_slices: [u8; P256_SCALAR_SLICES],
    /// `(r / s)` skew flag.
    pub s_p_skew: bool,
    /// `(r / s)` low borrow flag.
    pub s_p_borrow_low: bool,
    /// `(r / s)` mid borrow flag.
    pub s_p_borrow_mid: bool,
}

/// Full private/public input package for the passkey ownership circuit.
#[derive(Debug, Clone)]
pub struct PasskeyOwnershipCircuitInput {
    /// Public registry root.
    pub root: FieldElement,
    /// Public WebAuthn challenge bytes.
    pub challenge: [u8; 32],
    /// Public SHA-256 RP ID hash.
    pub rp_id_hash: [u8; 32],
    /// Private WebAuthn verifier witness.
    pub webauthn: WebAuthnWitness,
    /// Private slot commitments for the mixed authenticator set.
    pub slot_commitments: [FieldElement; PASSKEY_OWNERSHIP_NUM_SLOTS],
    /// Private index of the passkey proving authenticator slot.
    pub passkey_slot_index: u32,
    /// Private Merkle inclusion proof for the account leaf.
    pub inclusion_proof: MerkleInclusionProof<TREE_DEPTH>,
}

/// A generated passkey ownership proof and its public inputs.
#[derive(Debug, Clone, PartialEq)]
pub struct PasskeyOwnershipProof {
    /// WHIR/R1CS proof generated by ProveKit.
    pub proof: WhirR1CSProof,
    /// Registry root public input.
    pub root: FieldElement,
    /// WebAuthn challenge public input.
    pub challenge: [u8; 32],
    /// RP ID hash public input.
    pub rp_id_hash: [u8; 32],
}

/// Splits a P-256 big-endian 32-byte integer into the BigCurve limb order:
/// `[low_120_bits, mid_120_bits, high_16_bits]`.
#[must_use]
pub fn p256_be_bytes_to_limbs(bytes: [u8; 32]) -> [u128; P256_LIMBS] {
    fn fold(chunk: &[u8]) -> u128 {
        chunk
            .iter()
            .fold(0u128, |acc, byte| (acc << 8) | u128::from(*byte))
    }

    [
        fold(&bytes[17..32]),
        fold(&bytes[2..17]),
        fold(&bytes[0..2]),
    ]
}

/// Computes the demo passkey slot commitment used by Rust and Noir.
#[must_use]
pub fn passkey_slot_commitment(public_key: PasskeyPublicKey) -> FieldElement {
    let mut input = [Fq::ZERO; 16];
    input[0] = Fq::from_be_bytes_mod_order(DS_PASSKEY_SLOT);

    for (idx, limb) in public_key.x_limbs().into_iter().enumerate() {
        input[idx + 1] = Fq::from(limb);
    }
    for (idx, limb) in public_key.y_limbs().into_iter().enumerate() {
        input[idx + 1 + P256_LIMBS] = Fq::from(limb);
    }

    poseidon2::bn254::t16::permutation(&input)[1].into()
}

/// Computes the mixed authenticator-set leaf committed into `WorldIDRegistryV2`.
#[must_use]
pub fn mixed_authenticator_set_commitment(
    slot_commitments: [FieldElement; PASSKEY_OWNERSHIP_NUM_SLOTS],
) -> FieldElement {
    let mut input = [Fq::ZERO; 16];
    input[0] = Fq::from_be_bytes_mod_order(DS_MIXED_AUTH_SET);

    for (idx, commitment) in slot_commitments.into_iter().enumerate() {
        input[idx + 1] = *commitment;
    }

    poseidon2::bn254::t16::permutation(&input)[1].into()
}

fn byte_array_value(bytes: impl IntoIterator<Item = u8>) -> InputValue {
    InputValue::Vec(
        bytes
            .into_iter()
            .map(|byte| InputValue::Field(NoirElement::from(u64::from(byte))))
            .collect(),
    )
}

fn u128_array_value(values: impl IntoIterator<Item = u128>) -> InputValue {
    InputValue::Vec(
        values
            .into_iter()
            .map(|value| InputValue::Field(NoirElement::from(value)))
            .collect(),
    )
}

fn bool_value(value: bool) -> InputValue {
    InputValue::Field(NoirElement::from(value))
}

fn bounded_bytes_value(
    bytes: Vec<u8>,
    max_len: usize,
    name: &'static str,
) -> Result<InputValue, ProofError> {
    if bytes.len() > max_len {
        return Err(ProofError::InternalError(eyre::eyre!(
            "{name} length {} exceeds max {max_len}",
            bytes.len()
        )));
    }

    let mut storage = bytes;
    let len = storage.len();
    storage.resize(max_len, 0);

    let mut fields = std::collections::BTreeMap::new();
    fields.insert("storage".to_owned(), byte_array_value(storage));
    fields.insert(
        "len".to_owned(),
        InputValue::Field(NoirElement::from(len as u64)),
    );
    Ok(InputValue::Struct(fields))
}

impl NoirCircuitInput for PasskeyOwnershipCircuitInput {
    fn into_witness(self) -> Result<InputMap, ProofError> {
        let mut map = InputMap::new();
        map.insert("root".to_owned(), self.root.into_noir_value());
        map.insert("challenge".to_owned(), byte_array_value(self.challenge));
        map.insert("rp_id_hash".to_owned(), byte_array_value(self.rp_id_hash));

        let mut webauthn = std::collections::BTreeMap::new();
        webauthn.insert(
            "public_key_x".to_owned(),
            byte_array_value(self.webauthn.public_key_x),
        );
        webauthn.insert(
            "public_key_y".to_owned(),
            byte_array_value(self.webauthn.public_key_y),
        );
        webauthn.insert(
            "signature".to_owned(),
            byte_array_value(self.webauthn.signature),
        );
        webauthn.insert(
            "client_data_json".to_owned(),
            bounded_bytes_value(
                self.webauthn.client_data_json,
                CLIENT_DATA_JSON_MAX_LEN,
                "client_data_json",
            )?,
        );
        webauthn.insert(
            "authenticator_data".to_owned(),
            bounded_bytes_value(
                self.webauthn.authenticator_data,
                AUTHENTICATOR_DATA_MAX_LEN,
                "authenticator_data",
            )?,
        );
        webauthn.insert(
            "challenge_index".to_owned(),
            InputValue::Field(NoirElement::from(self.webauthn.challenge_index)),
        );
        webauthn.insert(
            "r_point_y".to_owned(),
            byte_array_value(self.webauthn.r_point_y),
        );
        webauthn.insert(
            "message_limbs".to_owned(),
            u128_array_value(self.webauthn.message_limbs),
        );
        webauthn.insert(
            "public_key_x_limbs".to_owned(),
            u128_array_value(self.webauthn.public_key_x_limbs),
        );
        webauthn.insert(
            "public_key_y_limbs".to_owned(),
            u128_array_value(self.webauthn.public_key_y_limbs),
        );
        webauthn.insert(
            "signature_r_limbs".to_owned(),
            u128_array_value(self.webauthn.signature_r_limbs),
        );
        webauthn.insert(
            "signature_s_limbs".to_owned(),
            u128_array_value(self.webauthn.signature_s_limbs),
        );
        webauthn.insert(
            "r_point_y_limbs".to_owned(),
            u128_array_value(self.webauthn.r_point_y_limbs),
        );
        webauthn.insert(
            "s_g_limbs".to_owned(),
            u128_array_value(self.webauthn.s_g_limbs),
        );
        webauthn.insert(
            "s_g_slices".to_owned(),
            byte_array_value(self.webauthn.s_g_slices),
        );
        webauthn.insert("s_g_skew".to_owned(), bool_value(self.webauthn.s_g_skew));
        webauthn.insert(
            "s_g_borrow_low".to_owned(),
            bool_value(self.webauthn.s_g_borrow_low),
        );
        webauthn.insert(
            "s_g_borrow_mid".to_owned(),
            bool_value(self.webauthn.s_g_borrow_mid),
        );
        webauthn.insert(
            "s_p_limbs".to_owned(),
            u128_array_value(self.webauthn.s_p_limbs),
        );
        webauthn.insert(
            "s_p_slices".to_owned(),
            byte_array_value(self.webauthn.s_p_slices),
        );
        webauthn.insert("s_p_skew".to_owned(), bool_value(self.webauthn.s_p_skew));
        webauthn.insert(
            "s_p_borrow_low".to_owned(),
            bool_value(self.webauthn.s_p_borrow_low),
        );
        webauthn.insert(
            "s_p_borrow_mid".to_owned(),
            bool_value(self.webauthn.s_p_borrow_mid),
        );

        let passkey_public_key = PasskeyPublicKey {
            x: self.webauthn.public_key_x,
            y: self.webauthn.public_key_y,
        };

        let mut merkle = std::collections::BTreeMap::new();
        merkle.insert(
            "leaf_index".to_owned(),
            InputValue::Field(NoirElement::from(self.inclusion_proof.leaf_index)),
        );
        merkle.insert(
            "siblings".to_owned(),
            InputValue::Vec(
                self.inclusion_proof
                    .siblings
                    .into_iter()
                    .map(NoirRepresentable::into_noir_value)
                    .collect(),
            ),
        );

        let mut inputs = std::collections::BTreeMap::new();
        inputs.insert("webauthn".to_owned(), InputValue::Struct(webauthn));
        inputs.insert(
            "public_key_x_limbs_field".to_owned(),
            u128_array_value(passkey_public_key.x_limbs()),
        );
        inputs.insert(
            "public_key_y_limbs_field".to_owned(),
            u128_array_value(passkey_public_key.y_limbs()),
        );
        inputs.insert(
            "slot_commitments".to_owned(),
            InputValue::Vec(
                self.slot_commitments
                    .into_iter()
                    .map(NoirRepresentable::into_noir_value)
                    .collect(),
            ),
        );
        inputs.insert(
            "passkey_slot_index".to_owned(),
            InputValue::Field(NoirElement::from(self.passkey_slot_index)),
        );
        inputs.insert("merkle_proof".to_owned(), InputValue::Struct(merkle));

        map.insert("inputs".to_owned(), InputValue::Struct(inputs));
        Ok(map)
    }
}

/// Builds the default seven-slot set containing one passkey at `slot_index`.
///
/// # Errors
/// Returns [`ProofError`] if `slot_index` is outside the demo slot set.
pub fn single_passkey_slot_set(
    public_key: PasskeyPublicKey,
    slot_index: usize,
) -> Result<[FieldElement; PASSKEY_OWNERSHIP_NUM_SLOTS], ProofError> {
    if slot_index >= PASSKEY_OWNERSHIP_NUM_SLOTS {
        return Err(ProofError::InternalError(eyre::eyre!(
            "slot_index {slot_index} is out of bounds"
        )));
    }

    let mut slots = [FieldElement::ZERO; PASSKEY_OWNERSHIP_NUM_SLOTS];
    slots[slot_index] = passkey_slot_commitment(public_key);
    Ok(slots)
}

#[cfg(all(
    feature = "embed-passkey-ownership-prover",
    not(target_arch = "wasm32")
))]
/// Generates a passkey ownership proof.
///
/// # Errors
/// Returns [`ProofError`] if witness conversion or ProveKit proof generation fails.
pub fn generate_passkey_ownership_proof(
    input: PasskeyOwnershipCircuitInput,
) -> Result<PasskeyOwnershipProof, ProofError> {
    use provekit_prover::Prove as _;

    const PKP_BYTES: &[u8] =
        include_bytes!(concat!(env!("OUT_DIR"), "/passkey_ownership_proof.pkp"));
    static PROVER: std::sync::OnceLock<Result<provekit_common::Prover, String>> =
        std::sync::OnceLock::new();

    let root = input.root;
    let challenge = input.challenge;
    let rp_id_hash = input.rp_id_hash;
    let witness = input.into_witness()?;
    let prover = PROVER.get_or_init(|| {
        provekit_common::register_ntt();
        provekit_common::file::deserialize(PKP_BYTES).map_err(|err| err.to_string())
    });
    let prover = prover
        .as_ref()
        .map_err(|err| ProofError::InternalError(eyre::eyre!(err.clone())))?
        .clone();
    let noir_proof = prover
        .prove(witness)
        .map_err(|err| ProofError::GenerationError(err.to_string()))?;

    Ok(PasskeyOwnershipProof {
        proof: noir_proof.whir_r1cs_proof,
        root,
        challenge,
        rp_id_hash,
    })
}

#[cfg(all(
    feature = "embed-passkey-ownership-verifier",
    not(target_arch = "wasm32")
))]
/// Verifies a passkey ownership proof with its embedded verifier artifact.
///
/// # Errors
/// Returns [`ProofError`] if the verifier cannot load or the proof is invalid.
pub fn verify_passkey_ownership_proof(proof: &PasskeyOwnershipProof) -> Result<(), ProofError> {
    use provekit_common::NoirProof;
    use provekit_verifier::Verify as _;

    const PKV_BYTES: &[u8] =
        include_bytes!(concat!(env!("OUT_DIR"), "/passkey_ownership_proof.pkv"));
    static VERIFIER: std::sync::OnceLock<Result<provekit_common::Verifier, String>> =
        std::sync::OnceLock::new();

    let verifier = VERIFIER.get_or_init(|| {
        provekit_common::register_ntt();
        provekit_common::file::deserialize(PKV_BYTES).map_err(|err| err.to_string())
    });
    let mut verifier = verifier
        .as_ref()
        .map_err(|err| ProofError::InternalError(eyre::eyre!(err.clone())))?
        .clone();

    let public_inputs =
        public_inputs_for_passkey_proof(proof.root, proof.challenge, proof.rp_id_hash);

    let noir_proof = NoirProof {
        public_inputs,
        whir_r1cs_proof: proof.proof.clone(),
    };
    verifier
        .verify(&noir_proof)
        .map_err(|err| ProofError::Verification(err.to_string()))
}

#[cfg(all(
    feature = "embed-passkey-ownership-verifier",
    not(target_arch = "wasm32")
))]
fn public_inputs_for_passkey_proof(
    root: FieldElement,
    challenge: [u8; 32],
    rp_id_hash: [u8; 32],
) -> provekit_common::PublicInputs {
    let values = std::iter::once(*root)
        .chain(challenge.map(|byte| Fq::from(u64::from(byte))))
        .chain(rp_id_hash.map(|byte| Fq::from(u64::from(byte))))
        .collect();
    provekit_common::PublicInputs::from_vec(values)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn splits_p256_bytes_into_bigcurve_limb_order() {
        let bytes = std::array::from_fn(|idx| idx as u8);

        assert_eq!(
            p256_be_bytes_to_limbs(bytes),
            [
                0x1112_1314_1516_1718_191a_1b1c_1d1e_1f,
                0x0203_0405_0607_0809_0a0b_0c0d_0e0f_10,
                0x0001,
            ]
        );
    }

    #[test]
    fn passkey_slot_commitment_is_deterministic_and_key_sensitive() {
        let key = PasskeyPublicKey {
            x: [1; 32],
            y: [2; 32],
        };
        let same = passkey_slot_commitment(key);

        let mut changed = key;
        changed.y[31] = 3;

        assert_eq!(same, passkey_slot_commitment(key));
        assert_ne!(same, passkey_slot_commitment(changed));
    }

    #[test]
    fn mixed_authenticator_set_commitment_is_slot_sensitive() {
        let key = PasskeyPublicKey {
            x: [1; 32],
            y: [2; 32],
        };
        let slot = passkey_slot_commitment(key);

        let left = mixed_authenticator_set_commitment([
            slot,
            FieldElement::ZERO,
            FieldElement::ZERO,
            FieldElement::ZERO,
            FieldElement::ZERO,
            FieldElement::ZERO,
            FieldElement::ZERO,
        ]);
        let right = mixed_authenticator_set_commitment([
            FieldElement::ZERO,
            slot,
            FieldElement::ZERO,
            FieldElement::ZERO,
            FieldElement::ZERO,
            FieldElement::ZERO,
            FieldElement::ZERO,
        ]);

        assert_ne!(left, right);
    }

    #[test]
    fn single_passkey_slot_set_places_commitment_at_requested_slot() {
        let key = PasskeyPublicKey {
            x: [9; 32],
            y: [10; 32],
        };
        let slots = single_passkey_slot_set(key, 2).unwrap();

        assert_eq!(slots[2], passkey_slot_commitment(key));
        assert!(
            slots
                .iter()
                .enumerate()
                .all(|(idx, value)| idx == 2 || *value == FieldElement::ZERO)
        );
    }
}
