[package]
name = "registry-gateway"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
alloy = { version = "1.0.22", default-features = false, features = ["json-rpc",
    "node-bindings",
    "rpc-client",
    "rpc-types-debug",
    "rpc-types-trace",
    "signer-aws"] }
anyhow = { workspace = true }
axum = { version = "0.7", features = ["macros", "json"] }
world-id-core = { path = "../../crates/world-id-core" }
dotenvy = "0.15"
hex = "0.4"
once_cell = "1"
parking_lot = "0.12"
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
tower-http = { version = "0.5", features = ["trace"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
world-id-core = { path = "../../crates/world-id-core" }
regex = "1.11.0"
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
