[workspace]
git_release_enable = true
git_release_latest = false
git_release_type = "auto"
pr_branch_prefix = "release-plz-oprf-node-"
pr_labels = ["release"]
release = false
release_always = false
publish = false
changelog_update = false

[[package]]
name = "world-id-oprf-node"
release = true
publish = false
git_only = true
changelog_update = true
changelog_path = "services/oprf-node/CHANGELOG.md"
