name: Circom Tests

on:
  push:
    branches:
      - main
    tags-ignore:
      - v*
  pull_request:
  
permissions:
  contents: read
  
jobs:
  test:
    name: Circuit Unit/KAT Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./circom/tests
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1 https://github.com/actions/checkout/releases/tag/v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0 https://github.com/actions/setup-node/releases/tag/v6.5.0
        with:
          node-version: 22
      - run: wget https://github.com/iden3/circom/releases/download/v2.2.2/circom-linux-amd64 -O circom && chmod +x circom && sudo mv circom /usr/local/bin/
      - run: npm ci
      - run: npm test

