name: Mobile Bench PR Command

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  actions: write
  pull-requests: read
  issues: write

jobs:
  dispatch:
    uses: worldcoin/mobile-bench-rs/.github/workflows/reusable-pr-command.yml@cf4416db0cd356a4434a524512de7e3716bd0799 # main branch https://github.com/worldcoin/mobile-bench-rs/commit/cf4416db0cd356a4434a524512de7e3716bd0799
    with:
      benchmark_workflow: .github/workflows/mobile-bench.yml
      crate_path: ./crates/zk-mobile-bench
      functions: '["zk_mobile_bench::bench_ownership_witness_generation","zk_mobile_bench::bench_ownership_proving","zk_mobile_bench::bench_ownership_proof_generation"]'
