name: Mobile Bench PR Auto

on:
  pull_request:
    types: [labeled]
  workflow_run:
    workflows: ["Rust CI"]
    types: [completed]

permissions:
  contents: read
  actions: write
  pull-requests: read
  checks: read

jobs:
  dispatch:
    uses: worldcoin/mobile-bench-rs/.github/workflows/reusable-pr-auto.yml@3a97e4c0fd5ef0683112c0385455aef5f239398f # main branch https://github.com/worldcoin/mobile-bench-rs/commit/3a97e4c0fd5ef0683112c0385455aef5f239398f
    with:
      benchmark_workflow: .github/workflows/mobile-bench.yml
      compile_gate_workflow_name: "Tests (stable)"
      crate_path: ./crates/zk-mobile-bench
      functions: '["zk_mobile_bench::bench_ownership_witness_generation","zk_mobile_bench::bench_ownership_proving","zk_mobile_bench::bench_ownership_proof_generation"]'
