name: Noir CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  ownership-proof:
    name: Noir CI (ownership-proof)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./crates/proof/noir/ownership-proof
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1 https://github.com/actions/checkout/releases/tag/v7.0.1
        with:
          persist-credentials: false
      - uses: noir-lang/noirup@7dbe69ccc78877f0200ffa5a40836c953d2cfd8f # v0.1.4 https://github.com/noir-lang/noirup/releases/tag/v0.1.4
        with:
          # See https://github.com/worldfnd/provekit, a specific nargo toolchain version is required
          toolchain: v1.0.0-beta.11
      - run: nargo fmt --check && nargo test
      - run: nargo execute --pedantic-solving

  authenticator-assertion:
    name: Noir CI (authenticator-assertion)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./crates/proof/noir/authenticator-assertion
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1 https://github.com/actions/checkout/releases/tag/v7.0.1
        with:
          persist-credentials: false
      - uses: noir-lang/noirup@7dbe69ccc78877f0200ffa5a40836c953d2cfd8f # v0.1.4 https://github.com/noir-lang/noirup/releases/tag/v0.1.4
        with:
          toolchain: v1.0.0-beta.11
      - run: nargo fmt --check && nargo test

  passkey-ownership-proof:
    name: Noir CI (passkey-ownership-proof)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./crates/proof/noir/passkey-ownership-proof
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1 https://github.com/actions/checkout/releases/tag/v7.0.1
        with:
          persist-credentials: false
      - uses: noir-lang/noirup@7dbe69ccc78877f0200ffa5a40836c953d2cfd8f # v0.1.4 https://github.com/noir-lang/noirup/releases/tag/v0.1.4
        with:
          toolchain: v1.0.0-beta.20
      - run: nargo fmt --check && nargo test
