name: Noir CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Noir CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./crates/proof/noir
    steps:
      - uses: actions/checkout@v6
      - uses: noir-lang/noirup@7dbe69ccc78877f0200ffa5a40836c953d2cfd8f # v0.1.4
        with:
          # See https://github.com/worldfnd/provekit, a specific nargo toolchain version is required
          toolchain: v1.0.0-beta.11
      - run: cd ownership-proof && nargo fmt --check && nargo test
