name: Prepare OPRF Node Release

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  prepare-oprf-node-release:
    name: Prepare OPRF Node Release
    runs-on: ubuntu-latest
    steps:
      - name: Run release-please release-pr
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          skip-github-release: true
