name: Rust CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

concurrency:
  group: >
    ${{ github.event_name == 'pull_request'
        && format('pr-{0}', github.event.pull_request.number)
        || format('main-{0}', github.run_id) }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  CARGO_TERM_COLOR: always

jobs:
  build-contracts:
    name: Build Contracts
    runs-on:
      group: arc-public-large-amd64-runner
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Cache contract artifacts
        id: cache-contracts
        uses: actions/cache@v4
        with:
          path: |
            contracts/out/
            crates/authenticator/abi/
            crates/issuer/abi/
            services/oprf-node/abi/
          key: contract-artifacts-${{ hashFiles('contracts/src/**', 'contracts/foundry.toml', 'contracts/foundry.lock', 'Makefile', 'contracts/test/core/**') }}
          # test contracts are also part of the cache because `CredentialSchemaIssuerRegistry.t.sol/MockOprfKeyRegistry.json` is used in Rust tests

      - name: Install Foundry
        if: steps.cache-contracts.outputs.cache-hit != 'true'
        uses: foundry-rs/foundry-toolchain@v1

      - name: Build contracts and extract ABIs
        if: steps.cache-contracts.outputs.cache-hit != 'true'
        run: make sol-build

      - name: Upload contract ABIs
        uses: actions/upload-artifact@v4
        with:
          name: contract-abis
          path: |
            crates/authenticator/abi/
            crates/issuer/abi/
            services/oprf-node/abi/
          retention-days: 1

      - name: Upload compiled contracts
        uses: actions/upload-artifact@v4
        with:
          name: contract-build-output
          path: contracts/out/
          retention-days: 1

  lint:
    name: Format and Clippy
    needs: build-contracts
    runs-on:
      group: arc-public-4xlarge-amd64-runner
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9
        with:
          toolchain: stable
          components: clippy

      - uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9
        with:
          toolchain: nightly
          components: rustfmt

      - name: Download contract ABIs
        uses: actions/download-artifact@v4
        with:
          name: contract-abis

      - name: Download compiled contracts
        uses: actions/download-artifact@v4
        with:
          name: contract-build-output
          path: contracts/out

      - name: Check code formatting
        run: cargo +nightly fmt --all -- --check

      - name: Run clippy
        env:
          CONTRACTS_PREBUILT: "1"
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

      - name: Run world-id-primitives clippy without crypto
        env:
          CONTRACTS_PREBUILT: "1"
        run: cargo clippy -p world-id-primitives --no-default-features -- -D warnings

  msrv:
    name: MSRV
    needs: build-contracts
    runs-on:
      group: arc-public-large-amd64-runner
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9
        with:
          toolchain: 1.87

      - name: Download contract ABIs
        uses: actions/download-artifact@v4
        with:
          name: contract-abis

      - name: Download compiled contracts
        uses: actions/download-artifact@v4
        with:
          name: contract-build-output
          path: contracts/out

      - name: Check Features
        env:
          CONTRACTS_PREBUILT: "1"
        run: |
          cargo check --all-features

  feature-resolution:
    name: Feature Resolution (cargo-hack)
    needs: build-contracts
    runs-on:
      group: arc-public-xlarge-amd64-runner
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9
        with:
          toolchain: stable

      - name: Download contract ABIs
        uses: actions/download-artifact@v4
        with:
          name: contract-abis

      - name: Install cargo-hack
        run: |
          cargo install cargo-hack --locked

      - name: Check Features
        run: |
          cargo hack check --each-feature --no-dev-deps --exclude world-id-test-utils --exclude generate-solidity-fixtures --exclude world-id-oprf-dev-client --exclude world-id-faux-issuer --exclude world-id-relay --exclude world-id-services-common

  test:
    name: Tests
    needs: build-contracts
    runs-on:
      group: arc-public-8xlarge-amd64-runner
    permissions:
      contents: read

    # Log in to Docker Hub if a token is provided to avoid public rate limiting
    env:
      IS_DOCKER_TOKEN_SET: ${{ (secrets.DOCKER_HUB_PULL_PUBLIC_IMAGES_TOKEN != '' && secrets.DOCKER_HUB_PULL_PUBLIC_IMAGES_USERNAME != '') && 'true' || 'false' }}

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0 https://github.com/docker/login-action/releases/tag/v3.6.0
        if: ${{ env.IS_DOCKER_TOKEN_SET == 'true' }}
        with:
          username: ${{ secrets.DOCKER_HUB_PULL_PUBLIC_IMAGES_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PULL_PUBLIC_IMAGES_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9
        with:
          toolchain: stable

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        # Anvil is used for integration tests

      - name: Download contract ABIs
        uses: actions/download-artifact@v4
        with:
          name: contract-abis

      - name: Download compiled contracts
        uses: actions/download-artifact@v4
        with:
          name: contract-build-output
          path: contracts/out

      - name: Run services
        run: |
          docker compose up -d
          sleep 5

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1 https://github.com/Swatinem/rust-cache/releases/tag/v2.9.1

      - name: Install cargo-nextest
        run: cargo install cargo-nextest --locked

      - name: Run tests
        env:
          CONTRACTS_PREBUILT: "1"
          TESTS_RPC_FORK_URL: ${{ secrets.TESTS_RPC_FORK_URL }}
        run: |
          cargo nextest run --profile ci --all-features --workspace
          cargo test --doc --all-features --workspace
          cargo nextest run --profile ci -p world-id-core --no-default-features
          cargo test --doc -p world-id-core --no-default-features

      - name: Run world-id-primitives tests without crypto
        env:
          CONTRACTS_PREBUILT: "1"
        run: cargo nextest run --profile ci -p world-id-primitives --no-default-features

      - name: Clean up services
        run: |
          docker compose down

  setup-test:
    name: Local Setup Test
    runs-on:
      group: arc-public-8xlarge-amd64-runner
    permissions:
      contents: read

    # Log in to Docker Hub if a token is provided to avoid public rate limiting
    env:
      IS_DOCKER_TOKEN_SET: ${{ (secrets.DOCKER_HUB_PULL_PUBLIC_IMAGES_TOKEN != '' && secrets.DOCKER_HUB_PULL_PUBLIC_IMAGES_USERNAME != '') && 'true' || 'false' }}

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0 https://github.com/docker/login-action/releases/tag/v3.6.0
        if: ${{ env.IS_DOCKER_TOKEN_SET == 'true' }}
        with:
          username: ${{ secrets.DOCKER_HUB_PULL_PUBLIC_IMAGES_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PULL_PUBLIC_IMAGES_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9
        with:
          toolchain: stable

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Build contracts
        run: |
          make sol-build

      - name: Run setup test
        run: |
          make setup-test

  deny:
    name: Cargo deny
    runs-on:
      group: arc-public-large-amd64-runner
    permissions:
      contents: read
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources

    continue-on-error: ${{ matrix.checks == 'advisories' }}

    # Log in to Docker Hub if a token is provided to avoid public rate limiting
    env:
      IS_DOCKER_TOKEN_SET: ${{ (secrets.DOCKER_HUB_PULL_PUBLIC_IMAGES_TOKEN != '' && secrets.DOCKER_HUB_PULL_PUBLIC_IMAGES_USERNAME != '') && 'true' || 'false' }}

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0 https://github.com/docker/login-action/releases/tag/v3.6.0
        if: ${{ env.IS_DOCKER_TOKEN_SET == 'true' }}
        with:
          username: ${{ secrets.DOCKER_HUB_PULL_PUBLIC_IMAGES_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PULL_PUBLIC_IMAGES_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4

      - uses: EmbarkStudios/cargo-deny-action@v2.0.14
        with:
          command: check ${{ matrix.checks }}

  docker:
    name: Test Docker build
    runs-on:
      group: arc-public-8xlarge-amd64-runner
    strategy:
      matrix:
        service:
          - indexer
          - gateway
    permissions:
      contents: read

    # Log in to Docker Hub if a token is provided to avoid public rate limiting
    env:
      IS_DOCKER_TOKEN_SET: ${{ (secrets.DOCKER_HUB_PULL_PUBLIC_IMAGES_TOKEN != '' && secrets.DOCKER_HUB_PULL_PUBLIC_IMAGES_USERNAME != '') && 'true' || 'false' }}

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0 https://github.com/docker/login-action/releases/tag/v3.6.0
        if: ${{ env.IS_DOCKER_TOKEN_SET == 'true' }}
        with:
          username: ${{ secrets.DOCKER_HUB_PULL_PUBLIC_IMAGES_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PULL_PUBLIC_IMAGES_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v6
        id: docker_build
        with:
          push: false
          load: true
          tags: ${{ matrix.service }}:latest
          cache-from: type=gha
          cache-to: "type=gha,mode=max"
          platforms: linux/amd64
          build-args: SERVICE_NAME=world-id-${{ matrix.service }}

      - name: Run services
        run: |
          docker compose up -d
          sleep 5

      - name: Run Docker container
        run: |
          # We run the http-only mode to avoid having to set up the RPC provider
          docker run -d --network host --env-file services/${{ matrix.service }}/.env.example --env LISTEN_ADDR=0.0.0.0:8080 --env RUN_MODE=http-only --name ${{ matrix.service }}-container ${{ matrix.service }}:latest

          # Wait for the application to start
          sleep 10

          # Output logs to GitHub action
          docker logs ${{ matrix.service }}-container

      - name: Health check Docker container
        run: curl -f http://0.0.0.0:8080/health

      - name: Clean up
        run: |
          docker stop ${{ matrix.service }}-container
          docker rm ${{ matrix.service }}-container
          docker compose down

  wasm:
    name: WASM Compatibility
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown

      - name: Check primitives compiles for WASM
        run: cargo check -p world-id-primitives --target wasm32-unknown-unknown
        env:
          RUSTUP_TOOLCHAIN: stable

      - name: Check primitives compiles for WASM (no-crypto)
        run: cargo check -p world-id-primitives --no-default-features --target wasm32-unknown-unknown
        env:
          RUSTUP_TOOLCHAIN: stable

  docs:
    name: Check docs
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      RUSTDOCFLAGS: -Dwarnings
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9
        with:
          toolchain: nightly
      - uses: dtolnay/install@cargo-docs-rs
      - run: |
          cargo +nightly docs-rs -p world-id-primitives
          cargo +nightly docs-rs -p world-id-authenticator
          cargo +nightly docs-rs -p world-id-core
